//
//  PromptProvider.swift
//  BifocalPrototyping
//
//  Created by Henry Lightfoot on 26/08/2025.
//

import SwiftUI

struct PromptStore {
    static let allPrompts: [String] = [
        "Your distress is real and never deserved.",
        "No matter how it feels, you’re trying your best. And you’re incredible.",
        "You deserve love and attention. Always.",
        "Your feelings should never be invalidated.",
        "I’m proud of you.",
        "It's okay to not be okay. Your feelings are valid.",
        "You are allowed to take up space.",
        "Your worth is not determined by your productivity.",
        "Surviving is something to be proud of.",
        "You have the right to say 'no' without guilt.",
        "Your sensitivity is a sign of strength, not weakness.",
        "It's okay to put your needs first.",
        "You are resilient, even when you don't feel like it.",
        "Every emotion you feel is a valid signal. Listen to it.",
        "You are not a burden. Your needs are important.",
        "The world is better for having you in it.",
        "You deserve to be heard and understood.",
        "It's brave to ask for help.",
        "Your past does not define your future.",
        "You are whole just as you are.",
        "It's okay to rest and recharge.",
        "You have the right to change your mind.",
        "Your perspective is unique and valuable.",
        "You are capable of getting through this.",
        "Be gentle with yourself today. You're doing the best you can.",
        "You are not responsible for other people's emotions.",
        "It's okay to feel overwhelmed. Take it one moment at a time.",
        "You deserve peace and tranquility.",
        "Your boundaries are important and deserve respect.",
        "You are more than your thoughts.",
        "It's okay to have needs and express them.",
        "Your strength is inspiring.",
        "You are allowed to make mistakes. They don't define you.",
        "Trust your intuition. It's there to guide you.",
        "You are worthy of all the good things that come your way.",
        "It's okay to feel lost sometimes. You will find your way.",
        "Your voice matters. Don't be afraid to use it.",
        "You are not alone in your struggles.",
        "It's okay to let go of what no longer serves you.",
        "You are a work in progress, and that's beautiful.",
        "Your capacity for feeling deeply is a gift.",
        "You deserve to feel safe and secure.",
        "It's okay to not have all the answers.",
        "You are allowed to feel joy, even in difficult times.",
        "Your heart knows the way. Trust it.",
        "You are stronger than you think.",
        "It's okay to have bad days. They don't erase your progress.",
        "You deserve compassion, especially from yourself.",
        "Your presence makes a difference.",
        "You are not too much. You are enough.",
        "It's okay to prioritize your mental health.",
        "You have the right to protect your energy.",
        "Your feelings are not an inconvenience.",
        "You are brave for facing each day.",
        "It's okay to feel angry. Your anger is valid.",
        "You are deserving of a life filled with happiness.",
        "Your story is important and deserves to be told.",
        "You are not defined by your diagnosis.",
        "It's okay to need reassurance.",
        "You are a masterpiece, even with the broken pieces.",
        "Your ability to feel is a superpower.",
        "You deserve to be treated with kindness and respect.",
        "It's okay to take a break from the world.",
        "You are not failing. You are learning and growing.",
        "Your light shines brightly, even on the darkest days.",
        "You are allowed to feel sad. Your sadness is valid.",
        "It's okay to not be positive all the time.",
        "You are worthy of love, just as you are.",
        "Your resilience is a testament to your strength.",
        "You are not what happened to you.",
        "It's okay to have setbacks. They are part of the journey.",
        "You deserve to be celebrated.",
        "Your dreams and aspirations are valid.",
        "You are not weak for feeling emotional.",
        "It's okay to need time to heal.",
        "You are a survivor, and your story matters.",
        "Your feelings are your allies.",
        "You deserve to have your needs met.",
        "It's okay to be vulnerable. It's a sign of courage.",
        "You are not a problem to be solved.",
        "Your existence is a gift.",
        "You are allowed to grieve what you've lost.",
        "It's okay to feel anxious. Your anxiety is a valid signal.",
        "You are worthy of a supportive community.",
        "Your imperfections make you beautiful.",
        "You are not obligated to explain yourself to anyone.",
        "It's okay to feel whatever you're feeling right now.",
        "You deserve to be happy and fulfilled.",
        "Your journey is your own, and it's valid.",
        "You are not alone in your pain.",
        "It's okay to have moments of doubt.",
        "You are a warrior, and you've fought many battles.",
        "Your feelings are a natural part of being human.",
        "You deserve to be loved unconditionally.",
        "It's okay to not be okay, even when others expect you to be.",
        "You are not a burden for needing support.",
        "Your capacity for empathy is a strength.",
        "You are allowed to have boundaries with anyone.",
        "It's okay to feel tired. You've been through a lot.",
        "You are enough, exactly as you are.",
        "Your pain is valid, no matter how small it may seem to others.",
        "You have the right to feel safe in your own body.",
        "It's okay to not have a linear healing journey.",
        "You are not responsible for fixing others.",
        "Your intuition is a powerful guide.",
        "You are allowed to take time for yourself.",
        "It's okay to feel disconnected sometimes.",
        "You are worthy of a life free from judgment.",
        "Your emotions are not a sign of weakness.",
        "You are not your intrusive thoughts.",
        "It's okay to have conflicting feelings.",
        "You deserve to be treated with gentleness.",
        "Your experiences have shaped you, but they don't define you.",
        "You are not too sensitive. The world is too harsh.",
        "It's okay to need space to process your emotions.",
        "You are a valuable human being.",
        "Your feelings are not an overreaction.",
        "You deserve to be seen and accepted for who you are.",
        "It's okay to have days where you can't do it all.",
        "You are not a failure for struggling.",
        "Your heart is capable of immense love and healing.",
        "You are allowed to feel proud of yourself.",
        "It's okay to feel numb sometimes.",
        "You are worthy of all the care and support you need.",
        "Your story is one of resilience and strength.",
        "You are not alone in feeling this way.",
        "It's okay to have needs that differ from others.",
        "You deserve to be surrounded by people who lift you up.",
        "Your feelings are a compass, guiding you toward what you need.",
        "You are not a burden for having complex emotions.",
        "It's okay to not be 'on' all the time.",
        "You are a survivor, and your strength is admirable.",
        "Your emotions are a vital part of your humanity.",
        "You deserve to have your boundaries honored.",
        "It's okay to feel things deeply.",
        "You are not defined by your worst moments.",
        "Your capacity for love is a beautiful thing.",
        "You are allowed to protect your peace.",
        "It's okay to feel uncertain about the future.",
        "You are worthy of a life filled with meaning and purpose.",
        "Your feelings are a valid response to your experiences.",
        "You are not too much for the right people.",
        "It's okay to need help navigating your emotions.",
        "You are a unique and irreplaceable individual.",
        "Your sensitivity allows you to experience the world in a profound way.",
        "You deserve to be loved for who you are, not who others want you to be.",
        "It's okay to have days where you feel fragile.",
        "You are not a burden for expressing your needs.",
        "Your journey of healing is a testament to your courage.",
        "You are allowed to feel joy without guilt.",
        "It's okay to feel overwhelmed by the world.",
        "You are worthy of a life where you feel understood.",
        "Your emotions are not something to be ashamed of.",
        "You are not responsible for other people's happiness.",
        "It's okay to take things at your own pace.",
        "You are a beautiful soul, inside and out.",
        "Your feelings are a sign that you are alive and aware.",
        "You deserve to be treated with patience and understanding.",
        "It's okay to have moments where you feel like giving up.",
        "You are not a burden for needing comfort.",
        "Your capacity for compassion is a gift to the world.",
        "You are allowed to have your own opinions and beliefs.",
        "It's okay to feel lost in your own mind sometimes.",
        "You are worthy of a life filled with love and laughter.",
        "Your feelings are a valid part of your human experience.",
        "You are not too emotional. You are emotionally aware.",
        "It's okay to need time to yourself to recharge.",
        "You are a strong and capable person.",
        "Your sensitivity is a sign of your deep connection to the world.",
        "You deserve to be with people who make you feel safe.",
        "It's okay to have days where you don't feel productive.",
        "You are not a burden for having needs.",
        "Your journey is valid, even if it looks different from others.",
        "You are allowed to feel your feelings without judgment.",
        "It's okay to feel sad, even when good things are happening.",
        "You are worthy of a life that feels authentic to you.",
        "Your emotions are not a flaw. They are a feature.",
        "You are not responsible for managing other people's expectations.",
        "It's okay to have moments of weakness. They don't define your strength.",
        "You are a survivor, and your story is one of hope.",
        "Your feelings are a valid and important part of who you are.",
        "You deserve to be loved without conditions.",
        "It's okay to not have it all figured out.",
        "You are not a burden for needing a listening ear.",
        "Your capacity for empathy makes you a powerful force for good.",
        "You are allowed to have your own needs and desires.",
        "It's okay to feel overwhelmed by your own emotions.",
        "You are worthy of a life where you feel seen and heard.",
        "Your emotions are not a sign of instability.",
        "You are not responsible for other people's actions.",
        "It's okay to take a step back and breathe.",
        "You are a resilient and beautiful human being.",
        "Your sensitivity is a sign of your humanity.",
        "You deserve to be treated with respect, always.",
        "It's okay to have days where you feel like you're not enough.",
        "You are not a burden for needing space.",
        "Your journey of self-discovery is a brave one.",
        "You are allowed to feel angry about injustice.",
        "It's okay to feel your emotions fully.",
        "You are worthy of a life filled with peace and contentment.",
        "Your feelings are a valid response to life's challenges.",
        "You are not too much. You are a whole universe.",
        "It's okay to need help from others.",
        "You are a unique and valuable part of this world.",
        "Your sensitivity is a sign of your deep capacity for love.",
        "You deserve to be with people who accept you for who you are.",
        "It's okay to have days where you feel disconnected from yourself.",
        "You are not a burden for having a mental illness.",
        "Your journey of healing is not a race.",
        "You are allowed to feel joy, even in the midst of pain.",
        "It's okay to feel overwhelmed by the expectations of others.",
        "You are worthy of a life that is true to your values.",
        "Your emotions are not a weakness. They are a source of strength.",
        "You are not responsible for other people's problems.",
        "It's okay to take a break from social media.",
        "You are a strong and courageous person.",
        "Your sensitivity is a sign of your awareness and intelligence.",
        "You deserve to be treated with kindness, especially by yourself.",
        "It's okay to have days where you feel like you're going backwards.",
        "You are not a burden for needing validation.",
        "Your journey of self-love is a revolutionary act.",
        "You are allowed to feel sad about the state of the world.",
        "It's okay to feel your feelings without needing to justify them.",
        "You are worthy of a life filled with genuine connections.",
        "Your feelings are a valid and necessary part of your experience.",
        "You are not too complicated. You are beautifully complex.",
        "It's okay to need reassurance and support.",
        "You are a resilient and inspiring individual.",
        "Your sensitivity is a sign of your ability to connect with others.",
        "You deserve to be with people who make you feel good about yourself.",
        "It's okay to have days where you don't want to talk to anyone.",
        "You are not a burden for having a chronic illness.",
        "Your journey of healing is a personal and sacred one.",
        "You are allowed to feel happiness, even if others are not.",
        "It's okay to feel overwhelmed by your own thoughts.",
        "You are worthy of a life that is filled with purpose and passion.",
        "Your emotions are not a burden. They are a guide.",
        "You are not responsible for other people's choices.",
        "It's okay to take a mental health day.",
        "You are a survivor, and your story has the power to heal others.",
        "Your feelings are a valid expression of your inner world.",
        "You deserve to be loved for your authentic self.",
        "It's okay to not be okay, and it's okay to ask for what you need.",
        "You are not a burden for needing a safe space.",
        "Your capacity for empathy is a superpower that can change the world.",
        "You are allowed to have your own dreams and pursue them.",
        "It's okay to feel overwhelmed by the demands of life.",
        "You are worthy of a life where you feel empowered and in control.",
        "Your emotions are not a sign of immaturity.",
        "You are not responsible for other people's drama.",
        "It's okay to take time to figure things out.",
        "You are a beautiful and resilient soul.",
        "Your sensitivity is a sign of your deep connection to your own heart.",
        "You deserve to be treated with love and compassion.",
        "It's okay to have days where you feel like you're not making progress.",
        "You are not a burden for needing a shoulder to cry on.",
        "Your journey of self-acceptance is a courageous one.",
        "You are allowed to feel angry about being mistreated.",
        "It's okay to feel your feelings without needing to fix them.",
        "You are worthy of a life filled with joy and adventure.",
        "Your feelings are a valid and important part of your healing process.",
        "You are not too much. You are a force of nature.",
        "It's okay to need help and support from a therapist.",
        "You are a unique and valuable human being with so much to offer.",
        "Your sensitivity is a sign of your ability to feel the beauty in the world.",
        "You deserve to be with people who celebrate your successes.",
        "It's okay to have days where you feel like you're all alone.",
        "You are not a burden for having a disability.",
        "Your journey of healing is a testament to your resilience and strength.",
        "You are allowed to feel joy, even when there is sadness in the world.",
        "It's okay to feel overwhelmed by your own past.",
        "You are worthy of a life that is filled with love and connection.",
        "Your emotions are not a burden to others.",
        "You are not responsible for other people's baggage.",
        "It's okay to take a break from the news and the world.",
        "You are a strong and capable person who can get through anything.",
        "Your sensitivity is a sign of your deep connection to your own truth.",
        "You deserve to be treated with respect and dignity.",
        "It's okay to have days where you feel like you're not good enough.",
        "You are not a burden for needing time to heal your wounds.",
        "Your journey of self-love is a beautiful and transformative one.",
        "You are allowed to feel sad about the things you can't change.",
        "It's okay to feel your feelings without needing to understand them.",
        "You are worthy of a life filled with peace and serenity.",
        "Your feelings are a valid and necessary part of your growth.",
        "You are not too sensitive. You are attuned to the world.",
        "It's okay to need help from your friends and family.",
        "You are a resilient and inspiring person who has overcome so much.",
        "Your sensitivity is a sign of your ability to love deeply.",
        "You deserve to be with people who make you feel safe and supported.",
        "It's okay to have days where you feel like you're not yourself.",
        "You are not a burden for having trauma.",
        "Your journey of healing is a process, not a destination.",
        "You are allowed to feel happiness, even if you feel guilty about it.",
        "It's okay to feel overwhelmed by the future.",
        "You are worthy of a life that is filled with meaning and joy.",
        "Your emotions are not a sign of weakness. They are a sign of your humanity.",
        "You are not responsible for other people's mistakes.",
        "It's okay to take time to rest and recover.",
        "You are a survivor, and your story is one of strength and resilience.",
        "Your feelings are a valid and important part of your identity.",
        "You deserve to be loved for who you are, flaws and all.",
        "It's okay to not have all the answers, and it's okay to be uncertain.",
        "You are not a burden for needing help to get through the day.",
        "Your capacity for empathy is a gift that can heal the world.",
        "You are allowed to have your own needs and to ask for them to be met.",
        "It's okay to feel overwhelmed by your own emotions and to seek help.",
        "You are worthy of a life where you feel loved and cherished.",
        "Your emotions are not a burden. They are a compass that points to your needs.",
        "You are not responsible for other people's expectations of you.",
        "It's okay to take a break from everything and just be.",
        "You are a beautiful and resilient human being who is capable of anything.",
        "Your sensitivity is a sign of your deep connection to the world around you.",
        "You deserve to be treated with kindness, compassion, and understanding.",
        "It's okay to have days where you feel like you're not making any progress.",
        "You are not a burden for needing a safe and supportive environment.",
        "Your journey of self-discovery is a courageous and beautiful one.",
        "You are allowed to feel angry about the injustices you have experienced.",
        "It's okay to feel your feelings without needing to rationalize them.",
        "You are worthy of a life filled with joy, laughter, and love.",
        "Your feelings are a valid and important part of your healing journey.",
        "You are not too much. You are a universe of wonder and beauty.",
        "It's okay to need help and support from a community of like-minded people.",
        "You are a unique and valuable human being with a purpose in this world.",
        "Your sensitivity is a sign of your ability to feel the pain and joy of others.",
        "You deserve to be with people who lift you up and inspire you to be your best self.",
        "It's okay to have days where you feel like you're not connected to anyone.",
        "You are not a burden for having a mental health condition.",
        "Your journey of healing is a testament to your strength, courage, and resilience.",
        "You are allowed to feel joy, even when there is pain and suffering in the world.",
        "It's okay to feel overwhelmed by your own past and to seek therapy.",
        "You are worthy of a life that is filled with love, connection, and belonging.",
        "Your emotions are not a burden to those who truly care about you.",
        "You are not responsible for other people's happiness or unhappiness.",
        "It's okay to take a break from the world and to focus on your own well-being.",
        "You are a strong and capable person who has the power to create the life you want.",
        "Your sensitivity is a sign of your deep connection to your own intuition and wisdom.",
        "You deserve to be treated with respect, dignity, and love.",
        "It's okay to have days where you feel like you're not good enough, but know that you are.",
        "You are not a burden for needing time and space to heal your emotional wounds.",
        "Your journey of self-love is a beautiful and transformative process of becoming whole.",
        "You are allowed to feel sad about the things you have lost and to grieve them fully.",
        "It's okay to feel your feelings without needing to understand them completely.",
        "You are worthy of a life filled with peace, serenity, and inner harmony.",
        "Your feelings are a valid and necessary part of your human experience and growth.",
        "You are not too sensitive. You are deeply connected to the heart of the world.",
        "It's okay to need help from your support system, and to lean on them when you need to.",
        "You are a resilient and inspiring person who has the power to overcome any obstacle.",
        "Your sensitivity is a sign of your ability to love with an open and compassionate heart.",
        "You deserve to be with people who make you feel safe, supported, and loved.",
        "It's okay to have days where you feel like you're not yourself, and to be gentle with yourself.",
        "You are not a burden for having experienced trauma, and you deserve to heal.",
        "Your journey of healing is a process of reclaiming your power and your voice.",
        "You are allowed to feel happiness, even if you feel like you don't deserve it.",
        "It's okay to feel overwhelmed by the future, and to take it one day at a time.",
        "You are worthy of a life that is filled with meaning, purpose, and joy.",
        "Your emotions are not a sign of weakness. They are a sign of your strength and humanity.",
        "You are not responsible for other people's choices, actions, or feelings.",
        "It's okay to take time to rest, recover, and recharge your batteries.",
        "You are a survivor, and your story is one of strength, resilience, and hope.",
        "Your feelings are a valid and important part of your identity and who you are.",
        "You deserve to be loved for who you are, with all your beautiful imperfections.",
        "It's okay to not have all the answers, and to be a work in progress.",
        "You are not a burden for needing help to get through the day, and it's okay to ask for it.",
        "Your capacity for empathy is a gift that can heal yourself and the world."
    ]
    
}
